### ISSUE TITLE
Why are there 3 classes (Stub, Proxy, SmartProxy) defined inside the interface?

### ISSUE THREAD

**Issue by afarber** [Himmele/Mindroid.java#1]
Hello Daniel, 

thank you for providing your framework.

I have a question about the pattern used in several files, for example in [mindroid/os/IRemoteCallback.java](https://github.com/Himmele/Mindroid.java/blob/master/src/mindroid/os/IRemoteCallback.java)

What is the purpose of the `Stub`, `Proxy`and `SmartProxy`classes there?

When to use `asBinder`and `asInterface`methods?

Greetings from Bochum
Alex

**Comment by Himmele** [comment]
Hello Alexander,

it is about having the Callback run in the correct thread context, which is
the context that created the callback.
The SmartProxy class first checks if it a thread-local call or a remote
(inter-thread) call.
Then is either calls the method directly (using the Stub) or it does
message passing to switch to the right thread context (using Proxy).

Hope that helps,
Daniel

2016-07-07 16:34 GMT+02:00 Alexander Farber notifications@github.com:
